services:
  postgres:
    image: postgres:18-bookworm
    container_name: booking-db
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5433:5432"
    volumes:
      - booking-data:/var/lib/postgresql

volumes:
  booking-data: